OT143-49 || Componente NewsDetail
alkemyTech/OT143-CLIENT pull request #26
Opened 2022-02-25 01:08 UTC by GuidoGagliardini

Creacion del componente NewsDetail que recibe por params el ID y muestra la noticia dinamicamente.
Creo componente Loadgin para mostrar un Spinner mientras carga la News.
![image](https://user-images.githubusercontent.com/64752492/155634204-2c6193df-3587-473f-bd24-ed0ba84aa05e.png)
![image](https://user-images.githubusercontent.com/64752492/155634223-07ee4327-b678-44d6-8ab0-22a90c1382b9.png)
![image](https://user-images.githubusercontent.com/64752492/155634234-dd339db3-c697-4887-9389-64d6c4872806.png)

2022-03-04 09:41 UTC, GauntStrelok commented on src/Components/News/Detail/NewsDetail.js
> +                alert("Error 404 no hay noticias");
Capaz es una buena idea setear el isFetching en false aca tambien

2022-03-04 09:41 UTC, GauntStrelok commented on src/Components/News/Detail/NewsDetail.js
> +                {console.log(news)}
Sacar este console log

2022-03-04 09:43 UTC, GauntStrelok commented on src/Components/News/Detail/NewsDetail.js
> +    <Title text={"Novedades"} />
El ticket dice especificamente que el titulo sera recibido por props

2022-03-08 05:15 UTC, cortiz2894 requested changes
* De momento comentar la llamada al endpoint. Esto se hará en una tarea mas adelante.
* Tratar de cumplir las especificaciones de la tarea sin adelantarse ya que hay proximos tickets para resolver las proximas funcionalidades.

2022-03-08 05:15 UTC, cortiz2894 commented on src/Components/News/Detail/NewsDetail.js
> +const NewsDetail = () => {
* El componente no recibe una prop con el titulo, la misma debera utilizarse al llamar al componente "<Title />", Linea : 34

2022-03-08 22:16 UTC, GuidoGagliardini commented on src/Components/News/Detail/NewsDetail.js
> +const NewsDetail = () => {
Listo, ya realice los cambios que hacian falta! GRacias!

2022-03-09 01:34 UTC, cortiz2894 approved these changes

2022-03-09 01:34 UTC, merged