ot143-77-activities-services-http  archivo de extension de metodos http para actividades
alkemyTech/OT143-CLIENT pull request #29
Opened 2022-02-25 14:37 UTC by lautp

Se creo el archivo que extiende el servicio privado http para las actividades.

2022-03-04 09:49 UTC, GauntStrelok requested changes, later dismissed

2022-03-04 09:49 UTC, GauntStrelok commented on src/Services/activitiesExtService.js
> +	Patch(`http://ongapi.alkemy.org/api/activities/${id}`, data, id);
Para que le mandas el id, si ya lo estaria recibiendo en el primer parametro?

2022-03-08 18:13 UTC, cortiz2894 approved these changes

2022-03-08 18:17 UTC, cortiz2894 reviewed
* Hay archivos con conflictos contra development

2022-03-09 18:59 UTC, merged