OT143-66 || Listado-Miembros-Backoffice
alkemyTech/OT143-CLIENT pull request #34
Opened 2022-02-26 00:10 UTC by GuidoGagliardini

Creacion del componente donde se muestran los miembros en una lista, con sus botones de Editar/Eliminar y en la parte superior el boton Crear que nos redirige a la furuta pagina de cracion de miembros.
![image](https://user-images.githubusercontent.com/64752492/155819506-656eac1c-cd74-4817-b64e-dde834ee87b4.png)

2022-03-04 10:14 UTC, GauntStrelok commented on src/Components/News/Detail/NewsDetail.js
> +import React, { useEffect,useState } from 'react';
Porque esta este archivo aca?

2022-03-04 10:15 UTC, GauntStrelok commented on src/Components/Members/MembersBackofficeList.js
> +        alert("Redirige a /backoffice/members/create")
Hacelo con un link, o con History de react, esto es parte de lo que se pide en el ticket

2022-03-04 10:16 UTC, GauntStrelok commented on src/Components/Members/MembersBackofficeList.js
> +    const crearClick = (e)=>{
para que esta este metodo creado?

2022-03-08 05:25 UTC, cortiz2894 requested changes
Contiene archivos y modificaciones que no pertenecen al branch. Deben ser cambios que quedaron colgados de otros branchs, asegurarse que no esten aca y solo esten en el branch que corresponde con la tarea.
Al ingresar a la ruta "/backoffice/categories" no muestra el listado como lo especifica la tarea. Agregar la ruta correspondiente y mostrar el componente.

2022-03-09 19:49 UTC, cortiz2894 approved these changes

2022-03-09 19:49 UTC, cortiz2894 commented on src/Components/Members/MembersBackofficeList.js
> +        {id:"1", nombre:"Cecilia Mendez" , imagen:imagenCM},
* Segun la especificación de la tarea el campo deberia ser "photo"

2022-03-09 19:49 UTC, cortiz2894 commented on src/Components/Members/MembersBackofficeList.js
> +                            <img src={miembro.imagen}  height="80px!important" />
* Utilizar un archivo css para dar estilos, las etiquetas de estilo en linea y el uso de "!important" se considera una "mala practica".

2022-03-09 19:50 UTC, merged