OT143-63 || Listado-Categorias-Backoffice
alkemyTech/OT143-CLIENT pull request #36
Opened 2022-02-26 15:21 UTC by GuidoGagliardini

Creacion de una tabla para listar las categorias. Utilizo la libreria moment de JS, para darle un formato a la fecha.
![image](https://user-images.githubusercontent.com/64752492/155848611-eadb53f2-fedc-40e2-a523-0a750c6e5f74.png)

2022-03-04 10:25 UTC, GauntStrelok commented on src/Components/Members/MembersBackofficeList.js
> +import React from 'react';
Porque esta este archivo en este branch?

2022-03-04 10:25 UTC, GauntStrelok commented on src/Components/News/Detail/NewsDetail.js
> +import React, { useEffect,useState } from 'react';
Porque esta esto en este branch?

2022-03-08 05:23 UTC, cortiz2894 requested changes
* Contiene archivos y modificaciones que no pertenecen al branch. Deben ser cambios que quedaron colgados de otros branchs, asegurarse que no esten aca y solo esten en el branch que corresponde con la tarea.
* Al ingresar a la ruta "/backoffice/categories" no muestra el listado como lo especifica la tarea. Agregar la ruta correspondiente y mostrar el componente.

2022-03-09 19:57 UTC, cortiz2894 approved these changes

2022-03-09 19:57 UTC, merged