OT143-68 || GET-Endpoint-PrivateApi
alkemyTech/OT143-CLIENT pull request #37
Opened 2022-02-26 15:51 UTC by GuidoGagliardini

Cracion de metodo GET del servicio privado de las API.
![image](https://user-images.githubusercontent.com/64752492/155849621-39a3c374-811c-4abe-a87d-e63c4e1e373e.png)

2022-03-04 10:27 UTC, GauntStrelok requested changes

2022-03-04 10:27 UTC, GauntStrelok commented on src/Components/Categories/CategoriesListBackoffice.js
> +import React from 'react';
Porque esta este archivo en este branch?

2022-03-04 10:27 UTC, GauntStrelok commented on src/Components/Members/MembersBackofficeList.js
> +import React from 'react';
Porque esta este archivo en este branch?

2022-03-04 10:27 UTC, GauntStrelok commented on src/Components/News/Detail/NewsDetail.js
> +import React, { useEffect,useState } from 'react';
Porque esta este archivo en este branch?

2022-03-04 10:27 UTC, GauntStrelok commented on src/Services/privateApiService.js
> +		.get(`${baseURL}/${id}`, config)
Que pasa si no le mando ID?

2022-03-09 20:04 UTC, cortiz2894 requested changes

2022-03-09 20:04 UTC, cortiz2894 commented on src/Services/privateApiService.js
> +		.then(res => console.log(res))
* Continuar la logica que utilizo el resto del equipo. Entiendo que el .then lo estan haciendo cuando se invoca al metodo en algun componente.

2022-03-13 19:53 UTC, merged