Formulario Edición / Creación de Testimonios
alkemyTech/OT143-CLIENT pull request #40
Opened 2022-02-26 19:39 UTC by LeoCoronel

Se crea componente formulara para edición y creación de testimonios.

[Ticket Jira](https://alkemy-labs.atlassian.net/browse/OT143-31?atlOrigin=eyJpIjoiZDE3MmNmZWIxZTljNDUxMDhiOTdlNTVmYzczN2U3ZTEiLCJwIjoiaiJ9)

![image](https://user-images.githubusercontent.com/36435141/155856767-2d4c8f08-d099-4264-bf33-3a6511b56342.png)

2022-03-04 10:39 UTC, GauntStrelok requested changes

2022-03-04 10:39 UTC, GauntStrelok commented on src/Components/Testimonials/TestimonialsForm.js
> +            !testimonials ? axios
Cuando es testimonials false?

2022-03-04 22:49 UTC, LeoCoronel commented on src/Components/Testimonials/TestimonialsForm.js
> +            !testimonials ? axios
Cuando no lo recibe en props

2022-03-06 19:46 UTC, GauntStrelok requested changes

2022-03-06 19:46 UTC, GauntStrelok commented on src/Components/Testimonials/TestimonialsForm.js
> +            !testimonials ? axios
La pregunta fue capciosa, por como definiste testimonials 
const testimonials = props.testimonials ? {
        id: props.testimonials.id,
        name: props.testimonials.name,
        description: props.testimonials.description,
        image: props.testimonials.image
    } : {
        id: uuid(),
        name: "",
        description: "",
        image: ""
    }

Testimonials nunca es false, fijate como lo arreglas

2022-03-16 22:25 UTC, merged