OT143-53 | slider para página "inicio"
alkemyTech/OT143-CLIENT pull request #6
Opened 2022-02-21 02:48 UTC by LeoCoronel

Feature: (https://alkemy-labs.atlassian.net/browse/OT143-53?atlOrigin=eyJpIjoiMjYyMjYzY2E5MmI4NDBlMDk1NDk2Yjg4NTRmY2RlZmMiLCJwIjoiaiJ9)[OT143-53]

Description: Se realiza slider de imágenes para pantalla inicio

Screenshot: 
![image](https://user-images.githubusercontent.com/36435141/154880882-a9d0910d-b267-49f3-8520-c0b5fdee331f.png)

2022-02-22 00:58 UTC, cortiz2894 requested changes

2022-02-22 00:58 UTC, cortiz2894 commented on src/Components/Carousel/Carousel.js
> +            console.log(response.data.data.map((img) => {
Eliminar el "console.log" que encierra el .map

2022-02-22 00:58 UTC, cortiz2894 commented on src/Components/Carousel/Carousel.js
> +                    images.push(img.image);
* Utilizar setImage() para actualizar el state.

2022-02-22 00:58 UTC, cortiz2894 commented on src/Components/Carousel/Carousel.js
> +                    desc.push(img.description)
* Utilizar setDesc() para actualizar el state.

2022-02-22 00:58 UTC, cortiz2894 commented on src/Components/Carousel/Carousel.js
> +            ));
* Luego del .map una vez que fue cargada la info del backend, podrias setear el state loaded en true.

2022-02-22 00:58 UTC, cortiz2894 commented on src/Components/Carousel/Carousel.js
> +            <img src={selectedImage} alt="portada" className={`carousel__portada ${loaded ? "loaded" : ""}`}  onLoad={() => setLoaded(true)} />
En vez de utilizar el onLoad podrias usar un condicional para mostrar el <img> cuando este en true el state loaded.
EJ: 
`{loaded && <img src={selectedImage} alt="portada" className='carousel__portada' />}`

2022-02-22 01:00 UTC, cortiz2894 commented
* Se debe cambiar el de branch al cual es debe hacerse el request, deberia ser "development" en lugar de "main"

2022-03-04 09:19 UTC, GauntStrelok requested changes

2022-03-04 09:19 UTC, GauntStrelok commented on package.json
> +<<<<<<< HEAD
Esto no esta bien mergeado, si necesitas ayuda con el mergeo, simplemente mandame un mensaje y te doy una mano para como se hace

2022-03-04 09:19 UTC, GauntStrelok commented on src/App.js
> +<<<<<<< HEAD
Mas problemas de mergeo en este archivo

2022-03-04 09:19 UTC, GauntStrelok commented on src/Components/Carousel/Carousel.js
> +        console.log(slides)
remover los console log

2022-03-04 09:19 UTC, GauntStrelok commented on yarn.lock
> +<<<<<<< HEAD
Problemas de mergeo aca tambien, propongo eliminar completamente el archivo yarn.lock para evitar problemas, o crearlo de nuevo de 0, por mas que muestre muchas diferencias.

2022-03-06 20:05 UTC, GauntStrelok commented
Hacer nuevo pull de development para poder mergear, y avisar por chat cuando se hizo para realizarlo lo mas rapido posible

2022-03-06 20:10 UTC, merged